bata/bata/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('menu.urls', namespace='menu')),
    path('hitung/', include('hitung.urls', namespace='hitung')),
    path('menu/', include('menu.urls', namespace='menu')),
]

bata/hitung/urls.py
from django.urls import path
from . views import *
app_name = 'hitung'

urlpatterns = [
    path('batamerah', batamerah, name='batamerah'),
    path('bataringan', bataringan, name='bataringan'),
    path('batako', batako, name='batako'),
    path('panduan', panduan, name='panduan'),
]

bata/menu/urls.py
from django.urls import path
from . views import *
app_name = 'menu'

urlpatterns = [
    path('', menu, name='menu'),
]

bata/hitung/models.py
from django.db import models

# Create your models here.

bata/menu/models.py
from django.db import models

# Create your models here.

bata/hitung/views.py
from django.shortcuts import render

# Create your views here.


def batamerah(request):

    return render(request, 'batamerah.html')


def bataringan(request):

    return render(request, 'bataringan.html')


def batako(request):

    return render(request, 'batako.html')


def panduan(request):

    return render(request, 'panduan.html')

bata/menu/views.py
from django.shortcuts import render

# Create your views here.


def menu(request):

    return render(request, 'menu.html')

bata/hitung/templates/batako.html
{%extends 'base2.html'%} {% load static %} {%block content%} <br /><br />
<center>
  <div class="row">
    <div class="column">
      <a href="{% url 'menu:menu' %}"><img src="{%static 'images/back.png'%}" alt="" id="back"></a>
      <br />
    </div>
    <div class="column">
      <a href="{% url 'hitung:batako' %}"><h4>Batako</h4></a>
      <br />
    </div>
    <div class="column">
      <a href="{% url 'hitung:batako' %}"><img src="{%static 'images/icon.png'%}" alt="" id="back"></a>
      <br />
    </div>
  </div>
  <br />

  <label for="n1">Tinggi Bangunan</label><br />
  <img src="{%static 'images/m.png'%}" alt="" id="icon2" />
  <input type="text" id="n1" /><br /><br />

  <label for="n2">Panjang Bangunan</label><br />
  <img src="{%static 'images/m.png'%}" alt="" id="icon2" />
  <input type="text" id="n2" /><br />

  <p id="lebihlengkap" onclick="openForm();">Lebih Detail <b>&#8645;</b></p>

  <div id="cdetail">
    <p id="lebihlengkap" onclick="closeForm();">Lebih Detail <b>&#8645;</b></p>
    <label for="n3">Harga per pcs (default = Rp. 2.500)</label><br />
    <img src="{%static 'images/rp.png'%}" alt="" id="icon3" />
    <input type="text" id="n3" /><br /><br />

    <label for="n3">Bata per m2 (default = 11)</label><br />
    <img src="{%static 'images/buah.png'%}" alt="" id="icon3" />
    <input type="text" id="n4" /><br /><br />
  </div>

  <button onclick="calc();" id="hitung">HITUNG</button><br />
  <br /><br />
  <label>Jumlah buah bata</label><br />
  <img src="{%static 'images/buah.png'%}" alt="" id="icon4" />
  <input type="text" id="result" /><br /><br />
  <label>Harga bata</label><br />

  <img src="{%static 'images/rp.png'%}" alt="" id="icon3" />
  <input type="text" id="harga" />
</center>

<script>
  function openForm() {
    document.getElementById("cdetail").style.display = "block";
  }
  function closeForm() {
    document.getElementById("cdetail").style.display = "none";
  }

  function calc() {
    var n1 = parseFloat(document.getElementById("n1").value);
    var n2 = parseFloat(document.getElementById("n2").value);
    var n3 = parseFloat(document.getElementById("n3").value);
    var n4 = parseFloat(document.getElementById("n4").value);

    var result = (document.getElementById("result").value =
      n1 * n2 * n4 || n1 * n2 * 11);
    document.getElementById("harga").value = result * n3 || result * 2500;
  }
</script>
{%endblock%}

bata/hitung/templates/batamerah.html
{%extends 'base2.html'%} {% load static %} {%block content%} <br /><br />
<center>
  <div class="row">
    <div class="column">
      <a href="{% url 'menu:menu' %}"><img src="{%static 'images/back.png'%}" alt="" id="back"></a>
      <br />
    </div>
    <div class="column">
      <a href="{% url 'hitung:batamerah' %}"><h4>Bata Merah</h4></a>
      <br />
    </div>
    <div class="column">
      <a href="{% url 'hitung:batako' %}"><img src="{%static 'images/icon.png'%}" alt="" id="back"></a>
      <br />
    </div>
  </div>
  <br />
 
  <label for="n1">Tinggi Bangunan</label><br />
  <img src="{%static 'images/m.png'%}" alt="" id="icon2" />
  <input type="text" id="n1" /><br /><br />

  <label for="n2">Panjang Bangunan</label><br />
  <img src="{%static 'images/m.png'%}" alt="" id="icon2" />
  <input type="text" id="n2" /><br />

  <p id="lebihlengkap"onclick="openForm();">Lebih Detail <b>&#8645;</b></p>
  
  <div id="cdetail" >
    <p id="lebihlengkap"onclick="closeForm();">Lebih Detail <b>&#8645;</b></p>
    <label for="n3">Harga per pcs (default = Rp. 600)</label><br />
    <img src="{%static 'images/rp.png'%}" alt="" id="icon3" />
    <input type="text" id="n3" /><br /><br />

    <label for="n3">Bata per m2 (default = 63)</label><br />
    <img src="{%static 'images/buah.png'%}" alt="" id="icon3" />
    <input type="text" id="n4" /><br /><br />

  </div>

  <button onclick="calc();" id="hitung">HITUNG</button><br />
  <br /><br />
  <label>Jumlah buah bata</label><br />
  <img src="{%static 'images/buah.png'%}" alt="" id="icon4" />
  <input type="text" id="result" /><br /><br />
  <label>Harga bata</label><br />

  <img src="{%static 'images/rp.png'%}" alt="" id="icon3" />
  <input type="text" id="harga" />
</center>

<script>
  function openForm() {
  document.getElementById("cdetail").style.display = "block";
}
function closeForm() {
  document.getElementById("cdetail").style.display = "none";
}

  function calc() {
    var n1 = parseFloat(document.getElementById("n1").value);
    var n2 = parseFloat(document.getElementById("n2").value);
    var n3 = parseFloat(document.getElementById("n3").value);
    var n4 = parseFloat(document.getElementById("n4").value);

    var result = (document.getElementById("result").value = n1*n2*n4 || n1 * n2 * 63);
    document.getElementById("harga").value = result * n3 || result * 600 ;
  }
</script>
{%endblock%}

bata/hitung/templates/bataringan.html
{%extends 'base2.html'%} {% load static %} {%block content%} <br /><br />
<center>
  <div class="row">
    <div class="column">
      <a href="{% url 'menu:menu' %}"><img src="{%static 'images/back.png'%}" alt="" id="back"></a>
      <br />
    </div>
    <div class="column">
      <a href="{% url 'hitung:bataringan' %}"><h4>Bata Ringan</h4></a>
      <br />
    </div>
    <div class="column">
      <a href="{% url 'hitung:batako' %}"><img src="{%static 'images/icon.png'%}" alt="" id="back"></a>
      <br />
    </div>
  </div>
  <br />

  <label for="n1">Tinggi Bangunan</label><br />
  <img src="{%static 'images/m.png'%}" alt="" id="icon2" />
  <input type="text" id="n1" /><br /><br />

  <label for="n2">Panjang Bangunan</label><br />
  <img src="{%static 'images/m.png'%}" alt="" id="icon2" />
  <input type="text" id="n2" /><br />

  <p id="lebihlengkap" onclick="openForm();">Lebih Detail <b>&#8645;</b></p>

  <div id="cdetail">
    <p id="lebihlengkap" onclick="closeForm();">Lebih Detail <b>&#8645;</b></p>
    <label for="n3">Harga per pcs (default = Rp. 5000)</label><br />
    <img src="{%static 'images/rp.png'%}" alt="" id="icon3" />
    <input type="text" id="n3" /><br /><br />

    <label for="n3">Bata per m2 (default = 8,3)</label><br />
    <img src="{%static 'images/buah.png'%}" alt="" id="icon3" />
    <input type="text" id="n4" /><br /><br />
  </div>

  <button onclick="calc();" id="hitung">HITUNG</button><br />
  <br /><br />
  <label>Jumlah buah bata</label><br />
  <img src="{%static 'images/buah.png'%}" alt="" id="icon4" />
  <input type="text" id="result" /><br /><br />
  <label>Harga bata</label><br />

  <img src="{%static 'images/rp.png'%}" alt="" id="icon3" />
  <input type="text" id="harga" />
</center>

<script>
  function openForm() {
    document.getElementById("cdetail").style.display = "block";
  }
  function closeForm() {
    document.getElementById("cdetail").style.display = "none";
  }

  function calc() {
    var n1 = parseFloat(document.getElementById("n1").value);
    var n2 = parseFloat(document.getElementById("n2").value);
    var n3 = parseFloat(document.getElementById("n3").value);
    var n4 = parseFloat(document.getElementById("n4").value);

    var result = (document.getElementById("result").value =
      n1 * n2 * n4 || n1 * n2 * 8.3);
    document.getElementById("harga").value = result * n3 || result * 5000;
  }
</script>
{%endblock%}

bata/menu/templates/menu.html
{%extends 'base2.html'%} {% load static %} {%block content%}
<center>
<div id="super">

  <div class="title">
    <a href="{% url 'menu:menu' %}"><h5>HITUNG BATA</h5></a>
    <p id="harga2">Harga Dapat Diubah</p>
   
  </div>
  <div class="main">
    
    <a href="{% url 'hitung:batamerah' %}">
      <div class="container">
      <img src="{%static 'images/batam.png'%}" alt="" class="gambarmenu">
      <p id="menu1">Bata Merah</p><br>
      <p id="menu2">Rp. 600</p>
    </div>
  </a>
  <a href="{% url 'hitung:bataringan' %}">
    <div class="container2">
      <img src="{%static 'images/batar.png'%}" alt="" class="gambarmenu">
      <p id="menu1">Bata Ringan</p><p id="menu2">Rp. 5.000</p></div>
      </a>

      <a href="{% url 'hitung:batako' %}">
      <div class="container3"> <img src="{%static 'images/batak.png'%}" alt="" class="gambarmenu">
      <p id="menu1">Batako&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</p>
      <p id="menu2">Rp. 2.500</p></div>
    </a>

    <div class="container4">
      <img src="{%static 'images/panduan.png'%}" alt="" class="gambarmenu">
      <p id="menu1">Panduan</p><p id="menu2"></p></div>
  </div>

</div>
</center>
{%endblock%}

bata/templates/base.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/styles.css'%}">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Titan+One&display=swap" rel="stylesheet">
  </head>
  <body>
    {%block content%} {%endblock%}
  </body>
</html>

bata/templates/base2.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/styles2.css'%}" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Titan+One&display=swap"
      rel="stylesheet"
    />
  </head>
  <body>
    {%block content%} {%endblock%}
  </body>
</html>